### ISSUE TITLE
Image Stretching issue in "behind the scenes" section

### ISSUE THREAD

**Issue by JATIN0926** [iot-lab-kiit/intern-fair#106]
when you are at "behind the scenes" section in homepage and you refresh the website , the image present there stretches for 2 seconds

**Comment by swastik-apk** [comment]
Is the issue resolved? I can't locate it on the hosted version, but it happens on localhost on About Us and Behind the Scenes.

**Comment by swastik-apk** [comment]
@JATIN0926 @Akangkha I have a working solution for this issue. I am raising a PR.
