### ISSUE TITLE
Improvement in Teams page cards UI 

### ISSUE THREAD

**Issue by JATIN0926** [iot-lab-kiit/intern-fair#108]
Ui of team's page card can be improved , in some screen sizes , name of team members come into 2 lines , can increase the width of cards accordingly to have a proper space , and names of members in one line

**Comment by Fixito** [comment]
Hi! I'd would like to work on this issue. Can you assign it to me?

**Comment by swastik-apk** [comment]
Hi @JATIN0926 ! 
I'd would like to work on this issue. Can you assign it to me?

1st year, CS department, KIIT.
